baseurl = "https://knowyourtoolset.com/"  # Include trailing slash
copyright = "Copyright © 2015-2021, Erik Dahl; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
# category = "categories"
tag = "tags"
# series = "series"

[params]
customCSS = ["css/custom.css"] # Include custom CSS files